### PR TITLE
Added Multi-threading to Java Controller

### PR DESCRIPTION
**Pull request by TheNumberOne**
Also added a random for a Player to use.

### CODE REVIEW

**Comment by spudone** [comment]
I wrote a quick & dirty Java multithreaded option before I saw your pull request.  I think yours is better, but feel free to take a look and use mine for ideas if you want.

https://github.com/spudone/ppcg-genetic-algorithms

**Comment by TheNumberOne** [comment]
@spudone You should probably add squares.clear() after line 151 in Board. The rest looks pretty good. That missing line caused quite a few problems while I was testing my bot.

**Comment by spudone** [comment]
Also, aside from the multithreading (and I know this wasn't your code): I think the genome should be a BitSet instead of a String.  It would be cleaner, avoiding the parseInt conversion.  Existing Player implementations would need conversion, though.

**Comment by spudone** [comment]
I also added a port of BlindFaith for testing which exposes more problems in the Java client.  I haven't ironed everything out yet, feel free to take a look:

https://github.com/spudone/ppcg-genetic-algorithms/blob/master/java/src/game/players/BlindFaith.java

**Comment by TheNumberOne** [comment]
@spudone There were a few problems with method breed in Game in the Original Controller. I recently updated my controller to fix those problems. A BitSet would be better but would break the other Java submissions.

**Pull request closed without merging**
